knp_paginator:

    page_range: 5

    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

    template:
        pagination: '_partials/pagination.html.twig'
        sortable:   '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'