security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER, ROLE_REPO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            user_checker: App\Security\Checker\UserChecker
            pattern: ^/
            context: user
            anonymous: true
            provider: users
            guard:
                authenticators:
                    - App\Security\Guard\Authenticator\LoginFormAuthenticator
            logout:
                path: /logout
                target: /
                invalidate_session: true

    access_control:
        - { path: ^/setup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/.*, role: ROLE_USER }
