security:
    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER, ROLE_REPO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/admin
            context: user
            provider: users
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_index
                use_referer: true
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true

    access_control:
        - { path: ^/admin/setup, role: PUBLIC_ACCESS }
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, role: PUBLIC_ACCESS }

        - { path: ^/admin, role: ROLE_USER }
        - { path: ^/.*, role: PUBLIC_ACCESS }
