security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER, ROLE_REPO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            user_checker: App\Security\Checker\UserChecker
            pattern: ^/admin
            context: user
            anonymous: true
            provider: users
            guard:
                authenticators:
                    - App\Security\Guard\Authenticator\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true

    access_control:
        - { path: ^/admin/setup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, role: ROLE_USER }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
