version: '3.6'

services:
  app:
    image: thecodingmachine/php:8.1-v4-apache-node16
    volumes:
      - .:/var/www/html
      - ./var/.bash_history:/home/docker/.bash_history
      - ${HOME}/.composer/:/home/docker/.composer/
    environment:
      - TZ=Europe/Berlin
      - APP_ENV=dev
      - APP_DEBUG=true
      - APACHE_DOCUMENT_ROOT=public
    depends_on:
      - database
    networks:
      apps:
        ipv4_address: 192.168.170.100

  database:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      apps:
        ipv4_address: 192.168.170.101

networks:
  apps:
    external: true
