FROM thecodingmachine/php:8.0-v4-apache-node14

ENV APACHE_DOCUMENT_ROOT="public/"

RUN touch /home/docker/.bashrc && printf '\
HISTFILE=~/bash_history\n\
PROMPT_COMMAND="history -a;history -n"\n\
umask 027\n' >> /home/docker/.bashrc

RUN sudo chown -R docker:docker /var/www/html/

VOLUME /var/www/html/
EXPOSE 80
