version: '3.6'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-Development
    volumes:
      - .:/var/www/html
      - ./var/bash_history:/home/docker/bash_history
      - ${HOME}/.ssh:/home/docker/.ssh
      - ${HOME}/.composer/:/home/docker/.composer/
    environment:
      - TZ=Europe/Berlin
      - APP_ENV=dev
      - APP_API_KEY=abc
    depends_on:
      - database
    networks:
      internal:
        ipv4_address: 172.16.83.10

  database:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    networks:
      internal:
        ipv4_address: 172.16.83.11

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.83.0/24
