app:
    resource: "../src/Controller"
    type: annotation

app_logout:
    path:     /logout

# has to be the last one
app_redirect:
    path: /{code}
    controller: \App\Controller\RedirectController