controllers:
    resource: ../src/Controller/
    type: annotation

app_logout:
    path: /admin/logout

kernel:
    resource: ../src/Kernel.php
    type: annotation

# has to be the last one
app_redirect:
    path: /{code}
    controller: \App\Controller\RedirectController
