parameters:
    locale: "%env(LOCALE)%"
        
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: ['doctrine.event_subscriber']

    App\:
        resource: '../src/*'
        exclude: '../src/{Controller,Domain,DependencyInjection,Entity,Model,Infrastructure,Tests,Kernel.php,bootstrap.php}'

#    # controller
    App\Controller\:
        resource: '../src/Controller/*'
        tags: ['controller.service_arguments']

    App\Infrastructure\ArgumentResolver\UserValueResolver: ~
    App\Infrastructure\Monolog\Processor\ExceptionProcessor: ~
    